branches:
  only:
    - master
    - /^production-[0-9]+/
sudo: required

env:
  global:
    # the repository name on Docker Hub
    - DOCKERHUB_REPO=iguanaproject/iguana

# stage order
stages:
  - test
  - build

# workaround template for the build stage to support multiple parallel builds
build_template: &build_tmp
  stage: build
  language: bash
  services:
    - docker
  before_script:
    # login to Docker Hub
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    # build the image and push it to Docker Hub
    - docker build -t $DOCKERHUB_REPO:$DOCKER_TAG --build-arg VARIANT=$VARIANT --build-arg USE_NGINX=$USE_NGINX .
    - docker push $DOCKERHUB_REPO:$DOCKER_TAG

jobs:
  include:
    # first test the code
    - stage: test
      language: python
      python:
        - "3.5"
      cache: pip
      addons:
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable
          - libexempi3
      install:
        - make development
        # requirement for coveralls.io
        - pip install coveralls
      before_script:
        # add the chromedriver binary to the PATH
        - export PATH=$PATH:`chromedriver-path`
      script:
        # run all tests
        make coverage +c
      # send coverage report to coveralls.io
      after_success:
        - pushd src
        - coveralls
        - popd

    # after that build the docker images
    - <<: *build_tmp
      env:
        - VARIANT=development
        - USE_NGINX=false
        - DOCKER_TAG=develop
    - <<: *build_tmp
      if: tag =~ ^production-[0-9]+
      env:
        - VARIANT=production
        - USE_NGINX=false
        - DOCKER_TAG=prod
    - <<: *build_tmp
      if: tag =~ ^production-[0-9]+
      env:
        - VARIANT=production
        - USE_NGINX=true
        - DOCKER_TAG=prod_nginx
