---
  - name: install nginx
    apt: name=nginx state=present

  - name: remove default site
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: create ssl-folder for nginx DH-Keys
    file: path=/etc/nginx/ssl state=directory

  - name: existance of DH-Keys
    stat: path=/etc/nginx/ssl/dhparam.pem
    register: dh

  - name: generate new DH-Keys
    command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
    when: dh.stat.exists == False

  - name: add secure nginx-configuration
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: create symlink
    file: src=/etc/nginx/sites-available/{{host}}  dest=/etc/nginx/sites-enabled/{{host}} state=link

  - name: add secure nginx-file
    template: >
      src=nginx_https_template.j2
      dest=/etc/nginx/sites-available/{{host}}

  - name: restart nginx
    service: name=nginx state=restarted
